volumes:
  vpurelux_rabbitmq:
networks:
  vpurelux:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    volumes:
      - vpurelux_rabbitmq:/var/lib/rabbitmq
    networks:
      - vpurelux
    ports:
      - "15672:15672"
      - "5672:5672"
